language: "en" # Supported languages -> hu, de, en

database:
  type: "mysql" # Supported types -> mysql, sqlite, mongodb
  mysql:
    host: localhost
    port: 3306
    database: coma112
    username: root
    password: ""
    # You shouldn't touch this part except if you are familiar with it.
    ssl: false
    certificateverification: false
    poolsize: 10
    lifetime: 1800000
  mongodb:
    host: localhost
    port: 27017
    database: reports
    username: ""
    password: ""

# This is the report item in the GUI.
report-item:
  material: PAPER
  name: "&2{player}&a's report (#{id})"
  lore:
    - ""
    - "&bTARGET: &a{target}"
    - "&bREASON: &a{reason}"
    - "&bDATE: &a{date}"
    - ""
    - "&aClick if you want to teleport to the target!"

# Menu Configuration
menu:
  back-item:
    amount: 1
    material: RED_STAINED_GLASS
    name: "&cBack"
    slot: 45
  forward-item:
    amount: 1
    material: GREEN_STAINED_GLASS
    name: "&aForward"
    slot: 53
  title: "&cREPORTS"
  size: 54
  update-tick: 2

